BEGIN;
SELECT set_config('app.user_id','f61b6f0f-821a-44d9-ba46-a64f7ef34f44',true);
SELECT set_config('app.org_id',(SELECT org_id::text FROM tasks WHERE external_ref LIKE 'theme:%' LIMIT 1),true);
SELECT set_config('app.role','ADMIN',true);
UPDATE tasks SET title='Животен циклус и управување со аналитички методи (QCSOP 009 / PP-QC-SOP-018) | Analytical Methods Lifecycle & Governance (QCSOP 009 / PP-QC-SOP-018)', updated_at=now() WHERE external_ref='theme:analytical-methods-lifecycle' AND is_deleted=false;
UPDATE tasks SET title='Наредба од CEO — санација на објектот и HVAC | CEO Order — Facility & HVAC Remediation', updated_at=now() WHERE external_ref='theme:ceo-facility-hvac-remediation' AND is_deleted=false;
UPDATE tasks SET title='Наредба од CEO — транзиција на генетика и деконтаминација | CEO Order — Genetics Transition & Decontamination', updated_at=now() WHERE external_ref='theme:ceo-genetics-transition' AND is_deleted=false;
UPDATE tasks SET title='Наредба од CEO — ослободување на Транша 1 и ЕУ GMP досие | CEO Order — Tranche 1 Release & EU GMP Dossier', updated_at=now() WHERE external_ref='theme:ceo-tranche1-release-gmp-dossier' AND is_deleted=false;
UPDATE tasks SET title='Наредба од CEO — ритам на неделно известување | CEO Order — Weekly Reporting Cadence', updated_at=now() WHERE external_ref='theme:ceo-weekly-reporting-cadence' AND is_deleted=false;
UPDATE tasks SET title='СОП за воздушна логистика при увоз на клонови од канабис | Cannabis Clone Import Air-Logistics SOP', updated_at=now() WHERE external_ref='theme:clone-import-logistics-sop' AND is_deleted=false;
UPDATE tasks SET title='Пакет документи и издавање CoA/CoQ (VariationF) | CoA/CoQ Document Suite & Issuance (VariationF)', updated_at=now() WHERE external_ref='theme:coa-coq-document-suite' AND is_deleted=false;
UPDATE tasks SET title='Повторно издавање на CPH Куманово PDF и корекција на SL | CPH Kumanovo PDF Re-issuance & SL Correction', updated_at=now() WHERE external_ref='theme:cph-pdf-reissue' AND is_deleted=false;
UPDATE tasks SET title='Циклус на рекалибрација на даталогери | Datalogger Recalibration Cycle', updated_at=now() WHERE external_ref='theme:datalogger-recalibration' AND is_deleted=false;
UPDATE tasks SET title='СОП-ови за инструменти и опрема | Instrument Equipment SOPs', updated_at=now() WHERE external_ref='theme:equipment-instrument-sops' AND is_deleted=false;
UPDATE tasks SET title='Шаблони за СОП за опрема и алатки за изработка | Equipment SOP Templates & Authoring Tooling', updated_at=now() WHERE external_ref='theme:equipment-sop-templates' AND is_deleted=false;
UPDATE tasks SET title='Фертигационен систем NetaJet/Netafim (PP-FERT-SOP-001) | NetaJet/Netafim Fertigation System (PP-FERT-SOP-001)', updated_at=now() WHERE external_ref='theme:fertigation-system-qualification' AND is_deleted=false;
UPDATE tasks SET title='Метода за верификација на страни материи (Ph.Eur. 2.8.2) | Foreign Matter Verification Method (Ph.Eur. 2.8.2)', updated_at=now() WHERE external_ref='theme:foreign-matter-verification' AND is_deleted=false;
UPDATE tasks SET title='Меморандум за релокација на GLP печатачи | GLP Printer Relocation Memo', updated_at=now() WHERE external_ref='theme:glp-printer-relocation' AND is_deleted=false;
UPDATE tasks SET title='Програма за GMP усогласеност и санација | GMP Compliance & Remediation Programme', updated_at=now() WHERE external_ref='theme:gmp-compliance-remediation' AND is_deleted=false;
UPDATE tasks SET title='Валидација на HPLC-DAD метода за канабиноиди (MVP-003) | HPLC-DAD Cannabinoid Assay Validation (MVP-003)', updated_at=now() WHERE external_ref='theme:hplc-cannabinoid-validation' AND is_deleted=false;
UPDATE tasks SET title='Етикетирање и контрола на етикети (QASOP 031) | Labeling & Label Control (QASOP 031)', updated_at=now() WHERE external_ref='theme:labeling-qasop-031' AND is_deleted=false;
UPDATE tasks SET title='Валидација на LoD / HMA метода (SAM a02.1/a02.2) | LoD / HMA Method Validation (SAM a02.1/a02.2)', updated_at=now() WHERE external_ref='theme:lod-hma-validation' AND is_deleted=false;
UPDATE tasks SET title='Логистика на материјали и магацинска контрола | Material Logistics & Warehouse Control', updated_at=now() WHERE external_ref='theme:material-logistics-warehouse' AND is_deleted=false;
UPDATE tasks SET title='Спецификации на материјали и производи (IMG / QCSOP 010) | Material & Product Specifications (IMG / QCSOP 010)', updated_at=now() WHERE external_ref='theme:material-product-specifications' AND is_deleted=false;
UPDATE tasks SET title='Микробиолошки план за мониторинг (QCPL 001) | Microbiological Monitoring Plan (QCPL 001)', updated_at=now() WHERE external_ref='theme:micro-monitoring-plan' AND is_deleted=false;
UPDATE tasks SET title='Кампања за микробиолошко-верификациско земање примероци (21 серија) | Micro-Verification Sampling Campaign (21 batches)', updated_at=now() WHERE external_ref='theme:micro-sampling-campaign' AND is_deleted=false;
UPDATE tasks SET title='Истрага на резултати надвор од очекуваното (QCSOP 019) | Out-of-Expected-Results Investigation (QCSOP 019)', updated_at=now() WHERE external_ref='theme:oox-investigation' AND is_deleted=false;
UPDATE tasks SET title='СОП за селекција на фенотип на канабис | Cannabis Phenotype Selection SOP', updated_at=now() WHERE external_ref='theme:phenotype-selection-sop' AND is_deleted=false;
UPDATE tasks SET title='Општи QA/QMS СОП-ови | QA/QMS General SOPs', updated_at=now() WHERE external_ref='theme:qa-qms-general-sops' AND is_deleted=false;
UPDATE tasks SET title='СОП-ови за работа на QC лабораторијата | QC Lab Operations SOPs', updated_at=now() WHERE external_ref='theme:qc-lab-operations-sops' AND is_deleted=false;
UPDATE tasks SET title='QC LIMS и системи за CoA/eCoA | QC LIMS & CoA/eCoA Systems', updated_at=now() WHERE external_ref='theme:qc-lims-coa-systems' AND is_deleted=false;
UPDATE tasks SET title='СОП за тестирање и земање примероци од вода (PP-QC-SOP-002) | QC Water Testing & Sampling SOP (PP-QC-SOP-002)', updated_at=now() WHERE external_ref='theme:qc-water-testing-sop' AND is_deleted=false;
UPDATE tasks SET title='Неделни QC планови и извештаи (SUMA ритам) | QC Weekly Plans & Reports (SUMA cadence)', updated_at=now() WHERE external_ref='theme:qc-weekly-plans-reports' AND is_deleted=false;
UPDATE tasks SET title='Рамковни СОП-ови за квалификација и валидација | Qualification & Validation Framework SOPs', updated_at=now() WHERE external_ref='theme:qualification-validation-framework' AND is_deleted=false;
UPDATE tasks SET title='Договор за квалитет/технички договор (Tetra Hip) | Quality/Technical Agreement (Tetra Hip)', updated_at=now() WHERE external_ref='theme:quality-technical-agreement' AND is_deleted=false;
UPDATE tasks SET title='Квалификација на RO систем за вода (PP/S/002) | RO Water System Qualification (PP/S/002)', updated_at=now() WHERE external_ref='theme:ro-water-qualification' AND is_deleted=false;
UPDATE tasks SET title='QC дневници за управување со примероци (QA_SOP_008) | QC Sample-Management Logbooks (QA_SOP_008)', updated_at=now() WHERE external_ref='theme:sample-management-logbooks' AND is_deleted=false;
UPDATE tasks SET title='СОП за транспорт на примероци до надворешни лаборатории (PP-QC-SOP-012) | Sample Transport to Outsourced Labs SOP (PP-QC-SOP-012)', updated_at=now() WHERE external_ref='theme:sample-transport-sop' AND is_deleted=false;
UPDATE tasks SET title='Изработка на СОП за QC земање примероци (PP-QC-SOP-017 / 008 / QCSOP 011) | QC Sampling SOP Authoring (PP-QC-SOP-017 / 008 / QCSOP 011)', updated_at=now() WHERE external_ref='theme:sampling-sop' AND is_deleted=false;
UPDATE tasks SET title='Студии на стабилност (QCSOP 018) | Stability Studies (QCSOP 018)', updated_at=now() WHERE external_ref='theme:stability-study' AND is_deleted=false;
UPDATE tasks SET title='Тестирање на патогени во супстрат (барање до надворешна лабораторија) | Substrate Pathogen Testing (External Lab Request)', updated_at=now() WHERE external_ref='theme:substrate-pathogen-test-request' AND is_deleted=false;
UPDATE tasks SET title='SUMA алатки и автоматизација | SUMA Tooling & Automation', updated_at=now() WHERE external_ref='theme:suma-tooling-automation' AND is_deleted=false;
UPDATE tasks SET title='Квалификација на добавувачи и набавки (QASOP 008/009) | Supplier & Procurement Qualification (QASOP 008/009)', updated_at=now() WHERE external_ref='theme:supplier-procurement-qualification' AND is_deleted=false;
SELECT count(*) AS bilingual_themes FROM tasks WHERE external_ref LIKE 'theme:%' AND title LIKE '%|%' AND is_deleted=false;
COMMIT;
